# Generated by Django 5.1 on 2025-03-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canchas',
            name='imagen',
        ),
        migrations.AddField(
            model_name='canchas',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
