# Generated by Django 5.1 on 2025-04-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
